<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\RebEasy.Domain\RebEasy.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.72.0" />
    <PackageReference Include="Google.Apis.Gmail.v1" Version="1.72.0.3966" />
  </ItemGroup>
</Project>
