<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RehabEasy.Domain\RehabEasy.Domain.csproj" />
    <ProjectReference Include="..\RehabEasy.Infrastructure\RehabEasy.Infrastructure.csproj" />
  </ItemGroup>
</Project>
